version: "3.8"

services:
  client:
    container_name: client
    build: 
      dockerfile: ./Dockerfile
    networks:
      - pocketnet
    ports:
      - "5173:3000"
    depends_on:
      - pocketbase

  pocketbase:
    container_name: pocketbase
    build: 
      dockerfile: ./pocketbase/Dockerfile
    networks:
      - pocketnet
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - "8090:8080"

networks:
  pocketnet:
    driver: bridge