name: Deploy

on:
  push: 
    branches: [ "main" ]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
      -name: Connect to the server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        password: ${{ secrets.DEPLOY_PWD }} 
        script: whoami